blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from posts.views import (
    index,
    search,
    post_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    IndexView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)

from marketing.views import email_list_signup

from mldeploy.views import coco , mnist

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index),
    #path('', IndexView.as_view(), name='home'),
    path('' , include('my_portfolio.urls')),
    # path('blog/', post_list, name='post-list'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    #path('create/', post_create, name='post-create'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('coco/' , coco , name="coco"),
    path('mnist/' , mnist , name="mnist"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_portfolio/urls.py
from django.urls import path
from . import views


app_name = 'my_portfolio'

urlpatterns = [
    path('' , views.index_main , name="index"),
    path('gallery/' , views.gallery, name="gallery"),
    path('contact/' , views.contact, name="contact"),
    path('about/' , views.about , name="about"),
    path('certi/' , views.certi , name="certi"),
]

my_portfolio/models.py
from django.db import models

# Create your models here.

my_portfolio/views.py
from django.shortcuts import render

# Create your views here.
def index_main(request):
    return render(request , "my_portfolio/index.html")


def gallery(request):
    return render(request , "my_portfolio/gallery.html")

def contact(request):
    return render(request , "my_portfolio/contact.html")

def certi(request):
    return render(request , "my_portfolio/certi.html")

def about(request):
    return render(request , "my_portfolio/about.html")

templates/my_portfolio/about.html
{% extends 'my_portfolio/base.html' %}

    {% block content %}
    {% load static %}

    <!-- Breadcrumb Area Start {% static 'my_portfolio/img/bg-img/108.jpg' %}-->
    <section class="breadcrumb-area bg-img bg-overlay jarallax" style="background-image: url({% static 'my_portfolio/img/bg-img/108.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2 class="page-title">About Me</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="{% url 'my_portfolio:index' %}"><i class="icon_house_alt"></i> Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">About</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Area End -->

    <!-- About Us Area Start {% static 'my_portfolio/img/bg-img/108.jpg' %}-->
    <div class="about-us-area section-padding-80-0 clearfix">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-lg-6">
                    <div class="about-us-content mb-80">
                        <h3 class="wow fadeInUp" data-wow-delay="100ms">CODE . COFFEE . REPEAT</h3>
                        <div class="line wow fadeInUp" data-wow-delay="200ms"></div>
                        <p class="wow fadeInUp" data-wow-delay="300ms">I am passionate about building excellent software , websites and applications that improves the lives of those around me. I specialize in creating software that intigrates Machine learning and Web-Development. </p>
                        <p class="wow fadeInUp" data-wow-delay="400ms">I am most fluent in Python based applications and Tensorflow . All of my work is produced locally from India. What would you do if you had a software developer available at your fingertips?</p>
                        <a class="btn alime-btn btn-2 mt-30 wow fadeInUp" data-wow-delay="500ms" href="{% url 'my_portfolio:contact' %}">Contact Me</a>
                    </div>
                </div>
                <div class="col-12 col-lg-6">
                    <div class="about-video-area mb-80 wow fadeInUp" data-wow-delay="100ms">
                        <img src="{% static 'my_portfolio/img/bg-img/17.jpg' %}" alt="">
                        <div class="video-icon">
                            <a href="https://www.youtube.com/watch?v=sSakBz_eYzQ" class="video-play-btn"><i class="arrow_triangle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About Us Area End -->

    <!-- Why Choose Us Area Start -->
    <section class="why-choose-us-area bg-gray section-padding-80-0 clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center wow fadeInUp" data-wow-delay="100ms">
                        <h2>Why Choose Me</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Single Why Choose Area -->
                <div class="col-md-6 col-lg-4">
                    <div class="why-choose-us-content text-center mb-80 wow fadeInUp" data-wow-delay="100ms">
                        <div class="chosse-us-icon">
                            <i class="fa fa-film" aria-hidden="true"></i>
                        </div>
                        <h4>Tailored To Your Needs</h4>
                        <p>The entire application will be tailored to your needs and requirements as like i always say the client is my eyes and their vision is my blueprint to build up for them.</p>
                    </div>
                </div>

                <!-- Single Why Choose Area -->
                <div class="col-md-6 col-lg-4">
                    <div class="why-choose-us-content text-center mb-80 wow fadeInUp" data-wow-delay="300ms">
                        <div class="chosse-us-icon">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </div>
                        <h4>Pixel-Perfect Code</h4>
                        <p>The entire code will be well documented for future reuseability and will be regularly tested , updated , patched and maintained to make it bug free</p>
                    </div>
                </div>

                <!-- Single Why Choose Area -->
                <div class="col-md-6 col-lg-4">
                    <div class="why-choose-us-content text-center mb-80 wow fadeInUp" data-wow-delay="500ms">
                        <div class="chosse-us-icon">
                            <i class="fa fa-heart" aria-hidden="true"></i>
                        </div>
                        <h4>Made With Love</h4>
                        <p>Each application , Website , etc. is made with love so that using the application is more of an experience to be felt rather than being tedious. </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Why Choose  us Area End -->

    <!-- Our Team Area Start -->
    <section class="our-team-area section-padding-80-50">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center wow fadeInUp" data-wow-delay="100ms">
                        <h2>My Specializations</h2>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Team Member Area -->
                <div class="col-md-6 col-xl-3">
                    <div class="team-content-area text-center mb-30 wow fadeInUp" data-wow-delay="100ms">
                        <div class="member-thumb">
                            <img src="{% static 'my_portfolio/img/bg-img/89.png' %}" alt="">
                        </div>
                        <h5>DeepLearning</h5>
                        <span>Coursera-DeepLearning.ai</span>
                        <div class="member-social-info">
                            <!-- <a href="#"><i class="ti-facebook"></i></a> -->
                            <!-- <a href="#"><i class="ti-twitter-alt"></i></a>-->
                            <a href="#"><i class="ti-id-badge"></i></a>
                            <!-- <a href="#"><i class="ti-pinterest"></i></a>-->
                        </div>
                    </div>
                </div>

                <!-- Team Member Area -->
                <div class="col-md-6 col-xl-3">
                    <div class="team-content-area text-center mb-30 wow fadeInUp" data-wow-delay="300ms">
                        <div class="member-thumb">
                            <img src="{% static 'my_portfolio/img/bg-img/90.jpg' %}" alt="">
                        </div>
                        <h5>MachineLearning</h5>
                        <span>Coursera-Stanford</span>
                        <div class="member-social-info">
                            <!-- <a href="#"><i class="ti-facebook"></i></a> -->
                            <!-- <a href="#"><i class="ti-twitter-alt"></i></a>-->
                            <a href="#"><i class="ti-id-badge"></i></a>
                            <!-- <a href="#"><i class="ti-pinterest"></i></a>-->
                        </div>
                    </div>
                </div>

                <!-- Team Member Area -->
                <div class="col-md-6 col-xl-3">
                    <div class="team-content-area text-center mb-30 wow fadeInUp" data-wow-delay="500ms">
                        <div class="member-thumb">
                            <img src="{% static 'my_portfolio/img/bg-img/91.png' %}" alt="">
                        </div>
                        <h5>Explore ML</h5>
                        <span>Google</span>
                        <div class="member-social-info">
                            <!-- <a href="#"><i class="ti-facebook"></i></a> -->
                            <!-- <a href="#"><i class="ti-twitter-alt"></i></a>-->
                            <a href="#"><i class="ti-id-badge"></i></a>
                            <!-- <a href="#"><i class="ti-pinterest"></i></a>-->
                        </div>
                    </div>
                </div>

                <!-- Team Member Area -->
                <div class="col-md-6 col-xl-3">
                    <div class="team-content-area text-center mb-30 wow fadeInUp" data-wow-delay="700ms">
                        <div class="member-thumb">
                            <img src="{% static 'my_portfolio/img/bg-img/92.jpg' %}" alt="">
                        </div>
                        <h5>DL&ML A-Z</h5>
                        <span>Udemy</span>
                        <div class="member-social-info">
                            <!-- <a href="#"><i class="ti-facebook"></i></a> -->
                            <!-- <a href="#"><i class="ti-twitter-alt"></i></a>-->
                            <a href="#"><i class="ti-id-badge"></i></a>
                            <a href="#"><i class="ti-id-badge"></i></a>
                            <!-- <a href="#"><i class="ti-pinterest"></i></a>-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center wow fadeInUp" data-wow-delay="700ms">
                    <a href="{% url 'my_portfolio:certi' %}" class="btn alime-btn btn-2 mt-15">View More</a>
                </div>
            </div>
            
        </div>
    </section>
    
    <!-- Our Team Area End -->

    {% endblock content %}

templates/my_portfolio/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>Shaurya- Profile</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static "my_portfolio/img/core-img/favicon.png" %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static "my_portfolio/style.css" %}">

</head>

<body>
    <!-- Preloader my_portfolio:index-->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- /Preloader {% url 'my_portfolio:index' %}-->

    <!-- Top Search Form Area -->
    <div class="top-search-area">
        <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <!-- Close bg-img/5.jpg-->
                        <button type="button" class="btn close-btn" data-dismiss="modal"><i class="ti-close"></i></button>
                        <!-- Form -->
                        <form action="index.html" method="post">
                            <input type="search" name="top-search-bar" class="form-control" placeholder="Search and hit enter...">
                            <button type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Header Area Start -->
    <header class="header-area">
        <!-- Main Header Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Classy Menu -->
                    <nav class="classy-navbar justify-content-between" id="alimeNav">

                        <!-- Logo "{% static "my_portfolio/img/core-img/AINOW1.png" %}"-->
                        <a class="nav-brand" href="{% url 'my_portfolio:index' %}"><img src="{% static "my_portfolio/img/core-img/AINOW1.png" %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Menu Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>
                            <!-- Nav Start "{% url 'my_portfolio:contact' %}"index-->
                            <div class="classynav">
                                <ul id="nav">
                                    <li class="active"><a href="{% url 'my_portfolio:index' %}">Home</a></li>
                                    <li><a href="#">My Work</a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'my_portfolio:certi' %}">- Certificates</a></li>
                                            <li><a href="{% url 'my_portfolio:gallery' %}">- Projects</a></li>
                                            
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'my_portfolio:about' %}" >About</a></li>
                                    <li><a href="{% url 'post-list' %}">Blog</a></li>
                                    <li><a href="{% url 'my_portfolio:contact' %}">Contact</a></li>
                                    <li><a href="{% static 'my_portfolio/resume.pdf' %}">Resume</a></li>
                                </ul>

                                <!-- Search Icon -->
                                <div class="search-icon" data-toggle="modal" data-target="#searchModal"><i class="ti-search"></i></div>
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->


    {% block content %}
    {% endblock content %}

    <!-- Follow Area Start https://www.linkedin.com/in/shaurya-sinha-71890617b/-->
    <section class="follow-area clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-heading text-center">
                        <h2>Follow Linkedin</h2>
                        <a href = "https://www.linkedin.com/in/shaurya-sinha-71890617b/"><p>@Shaurya_Sinha</p></a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Instagram Feed Area -->
        <div class="instragram-feed-area owl-carousel">
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/200.png" %}" alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/300.png" %}" alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/400.png" %}"alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/500.jpg" %}" alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/600.jpg" %}" alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
            <!-- Single Instagram Item -->
            <div class="single-instagram-item">
                <img src="{% static "my_portfolio/img/bg-img/700.jpg" %}" alt="">
                <div class="instagram-hover-content text-center d-flex align-items-center justify-content-center">
                    <a href="#">
                        <i class="ti-github" aria-hidden="true"></i>
                        <span>Shaurya_Sinha</span>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- Follow Area End -->

    <!-- Footer Area Start -->
    <footer class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-content d-flex align-items-center justify-content-between">
                        
                        <!-- Footer Logo "{% static "my_portfolio/img/core-img/AINOW1.png" %}"-->
                        <div class="footer-logo">
                            <a href="#"><img src="{% static "my_portfolio/img/core-img/AINOW1.png" %}" alt=""></a>
                        </div>
                        <!-- Social Info www.linkedin.com/in/shaurya-sinha-71890617b-->
                        <div class="social-info">
                            <a href="https://github.com/shauryabit2k18"><i class="ti-github" aria-hidden="true"></i></a>
                            <a href="#"><i class="ti-twitter-alt" aria-hidden="true"></i></a>
                            <a href="www.linkedin.com/in/shaurya-sinha-71890617b"><i class="ti-linkedin" aria-hidden="true"></i></a>
                            <a href="#"><i class="ti-facebook" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Area End -->

    <!-- **** All JS Files ***** -->
    <!-- jQuery 2.2.4 "{% static "my_portfolio/js/default-assets/active.js" %}"-->
    <script src="{% static "my_portfolio/js/jquery.min.js" %}"></script>
    <!-- Popper -->
    <script src="{% static "my_portfolio/js/popper.min.js" %}"></script>
    <!-- Bootstrap -->
    <script src="{% static "my_portfolio/js/bootstrap.min.js" %}"></script>
    <!-- All Plugins -->
    <script src="{% static "my_portfolio/js/alime.bundle.js" %}"></script>
    <!-- Active -->
    <script src="{% static "my_portfolio/js/default-assets/active.js" %}"></script>

</body>

</html>

templates/my_portfolio/contact.html
{% extends 'my_portfolio/base.html' %}

    {% block content %}
    {% load static %}


    <!-- Breadcrumb Area Start {% static 'my_portfolio/img/bg-img/38.jpg' %}-->
    <section class="breadcrumb-area bg-img bg-overlay jarallax" style="background-image: url({% static 'my_portfolio/img/bg-img/108.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcrumb-content text-center">
                        <h2 class="page-title">Contact</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="/"><i class="icon_house_alt"></i> Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Contact</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Area End -->

    <!-- Contact Area Start -->
    <div class="contact-area section-padding-80-50">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <h2 class="contact-title mb-30">Let’s Work <br>Together</h2>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <!-- Contact Info -->
                    <div class="contact-info mb-30">
                        <p>Email</p>
                        <a href="mailto:shaurya.r.sinha2000@gmail.com">shaurya.r.sinha2000@gmail.com</a>
                    </div>
                    <!-- Contact Info -->
                    <div class="contact-info mb-30">
                        <p>Call Me</p>
                        <a href="#">+91-0-7016416673</a>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <!-- Contact Info -->
                    <div class="contact-info mb-30">
                        <p>Location</p>
                        <a href="#">India</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Area End -->

    <!-- Map Area Start -->
    <div class="map-area section-padding-0-80">
        <div class="container">
            <div id="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4021.2230731307436!2d69.83576832190913!3d22.364032999425376!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjLCsDIxJzUwLjUiTiA2OcKwNTAnMTMuNSJF!5e1!3m2!1sen!2sin!4v1587115512839!5m2!1sen!2sin" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
    </div>
    <!-- Map Area End -->

    {% endblock content %}